In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import pickle

In [2]:
df=pd.read_csv('dataset-uci.csv')
df.head()

Gallstone Status  Age  Gender  Comorbidity  Coronary Artery Disease (CAD)  \
0                 0   50       0            0                              0   
1                 0   47       0            1                              0   
2                 0   61       0            0                              0   
3                 0   41       0            0                              0   
4                 0   42       0            0                              0   

   Hypothyroidism  Hyperlipidemia  Diabetes Mellitus (DM)  Height  Weight  \
0               0               0                       0     185    92.8   
1               0               0                       0     176    94.5   
2               0               0                       0     171    91.1   
3               0               0                       0     168    67.7   
4               0               0                       0     178    89.6   

   ...  High Density Lipoprotein (HDL)  Triglyceride  \
0  ...                            40.0         134.0   
1  ...                            43.0         103.0   
2  ...                            43.0          69.0   
3  ...                            59.0          53.0   
4  ...                            30.0         326.0   

   Aspartat Aminotransferaz (AST)  Alanin Aminotransferaz (ALT)  \
0                            20.0                          22.0   
1                            14.0                          13.0   
2                            18.0                          14.0   
3                            20.0                          12.0   
4                            27.0                          54.0   

   Alkaline Phosphatase (ALP)  Creatinine  Glomerular Filtration Rate (GFR)  \
0                        87.0        0.82                            112.47   
1                        46.0        0.87                            107.10   
2                        66.0        1.25                             65.51   
3                        34.0        1.02                             94.10   
4                        71.0        0.82                            112.47   

   C-Reactive Protein (CRP)  Hemoglobin (HGB)  Vitamin D  
0                       0.0              16.0       33.0  
1                       0.0              14.4       25.0  
2                       0.0              16.2       30.2  
3                       0.0              15.4       35.4  
4                       0.0              16.8       40.6  

[5 rows x 39 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Gallstone Status                                319 non-null    int64  
 1   Age                                             319 non-null    int64  
 2   Gender                                          319 non-null    int64  
 3   Comorbidity                                     319 non-null    int64  
 4   Coronary Artery Disease (CAD)                   319 non-null    int64  
 5   Hypothyroidism                                  319 non-null    int64  
 6   Hyperlipidemia                                  319 non-null    int64  
 7   Diabetes Mellitus (DM)                          319 non-null    int64  
 8   Height                                          319 non-null    int64  
 9   Weight                                     

In [4]:
df.isnull().sum()

Gallstone Status                                  0
Age                                               0
Gender                                            0
Comorbidity                                       0
Coronary Artery Disease (CAD)                     0
Hypothyroidism                                    0
Hyperlipidemia                                    0
Diabetes Mellitus (DM)                            0
Height                                            0
Weight                                            0
Body Mass Index (BMI)                             0
Total Body Water (TBW)                            0
Extracellular Water (ECW)                         0
Intracellular Water (ICW)                         0
Extracellular Fluid/Total Body Water (ECF/TBW)    0
Total Body Fat Ratio (TBFR) (%)                   0
Lean Mass (LM) (%)                                0
Body Protein Content (Protein) (%)                0
Visceral Fat Rating (VFR)                         0
Bone Mass (B

In [5]:
df.duplicated().sum()

0

In [6]:
df.describe()

Gallstone Status         Age      Gender  Comorbidity  \
count        319.000000  319.000000  319.000000   319.000000   
mean           0.495298   48.068966    0.492163     0.335423   
std            0.500763   12.114558    0.500724     0.517340   
min            0.000000   20.000000    0.000000     0.000000   
25%            0.000000   38.500000    0.000000     0.000000   
50%            0.000000   49.000000    0.000000     0.000000   
75%            1.000000   56.000000    1.000000     1.000000   
max            1.000000   96.000000    1.000000     3.000000   

       Coronary Artery Disease (CAD)  Hypothyroidism  Hyperlipidemia  \
count                     319.000000      319.000000      319.000000   
mean                        0.037618        0.028213        0.025078   
std                         0.190568        0.165841        0.156609   
min                         0.000000        0.000000        0.000000   
25%                         0.000000        0.000000        0.000000   
50%                         0.000000        0.000000        0.000000   
75%                         0.000000        0.000000        0.000000   
max                         1.000000        1.000000        1.000000   

       Diabetes Mellitus (DM)     Height      Weight  ...  \
count              319.000000  319.00000  319.000000  ...   
mean                 0.134796  167.15674   80.564890  ...   
std                  0.342042   10.05303   15.709069  ...   
min                  0.000000  145.00000   42.900000  ...   
25%                  0.000000  159.50000   69.600000  ...   
50%                  0.000000  168.00000   78.800000  ...   
75%                  0.000000  175.00000   91.250000  ...   
max                  1.000000  191.00000  143.500000  ...   

       High Density Lipoprotein (HDL)  Triglyceride  \
count                      319.000000    319.000000   
mean                        49.475549    144.502163   
std                         17.718701     97.904493   
min                         25.000000      1.390000   
25%                         40.000000     83.000000   
50%                         46.500000    119.000000   
75%                         56.000000    172.000000   
max                        273.000000    838.000000   

       Aspartat Aminotransferaz (AST)  Alanin Aminotransferaz (ALT)  \
count                      319.000000                    319.000000   
mean                        21.684953                     26.855799   
std                         16.697605                     27.884413   
min                          8.000000                      3.000000   
25%                         15.000000                     14.250000   
50%                         18.000000                     19.000000   
75%                         23.000000                     30.000000   
max                        195.000000                    372.000000   

       Alkaline Phosphatase (ALP)  Creatinine  \
count                  319.000000  319.000000   
mean                    73.112539    0.800611   
std                     24.181069    0.176433   
min                      7.000000    0.460000   
25%                     58.000000    0.650000   
50%                     71.000000    0.790000   
75%                     86.000000    0.920000   
max                    197.000000    1.460000   

       Glomerular Filtration Rate (GFR)  C-Reactive Protein (CRP)  \
count                        319.000000                319.000000   
mean                         100.818903                  1.853856   
std                           16.971396                  4.989591   
min                           10.600000                  0.000000   
25%                           94.170000                  0.000000   
50%                          104.000000                  0.215000   
75%                          110.745000                  1.615000   
max                          132.000000                 43.400000   

       Hemoglobin (HGB)   Vitam

In [36]:
num_features_max={}
for i in df.columns:
    
    if df[i].nunique()>10:

        num_features_max[i]=np.max(df[[i]])

num_features_max

{'Age': 96,
 'Height': 191,
 'Weight': 143.5,
 'Body Mass Index (BMI)': 49.7,
 'Total Body Water (TBW)': 66.2,
 'Extracellular Water (ECW)': 27.8,
 'Intracellular Water (ICW)': 57.1,
 'Extracellular Fluid/Total Body Water (ECF/TBW)': 52.0,
 'Total Body Fat Ratio (TBFR) (%)': 50.92,
 'Lean Mass (LM) (%)': 93.67,
 'Body Protein Content (Protein) (%)': 24.81,
 'Visceral Fat Rating (VFR)': 31,
 'Bone Mass (BM)': 4.0,
 'Muscle Mass (MM)': 78.8,
 'Obesity (%)': 1954.0,
 'Total Fat Content (TFC)': 62.5,
 'Visceral Fat Area (VFA)': 41.0,
 'Visceral Muscle Area (VMA) (Kg)': 41.1,
 'Glucose': 575.0,
 'Total Cholesterol (TC)': 360.0,
 'Low Density Lipoprotein (LDL)': 293.0,
 'High Density Lipoprotein (HDL)': 273.0,
 'Triglyceride': 838.0,
 'Aspartat Aminotransferaz (AST)': 195.0,
 'Alanin Aminotransferaz (ALT)': 372.0,
 'Alkaline Phosphatase (ALP)': 197.0,
 'Creatinine': 1.46,
 'Glomerular Filtration Rate (GFR)': 132.0,
 'C-Reactive Protein (CRP)': 43.4,
 'Hemoglobin (HGB)': 18.8,
 'Vitamin D': 5

In [35]:
num_features_min={}
for i in df.columns:
    
    if df[i].nunique()>10:

        num_features_min[i]=np.min(df[[i]])

num_features_min

{'Age': 20,
 'Height': 145,
 'Weight': 42.9,
 'Body Mass Index (BMI)': 17.4,
 'Total Body Water (TBW)': 13.0,
 'Extracellular Water (ECW)': 9.0,
 'Intracellular Water (ICW)': 13.8,
 'Extracellular Fluid/Total Body Water (ECF/TBW)': 29.23,
 'Total Body Fat Ratio (TBFR) (%)': 6.3,
 'Lean Mass (LM) (%)': 48.99,
 'Body Protein Content (Protein) (%)': 5.56,
 'Visceral Fat Rating (VFR)': 1,
 'Bone Mass (BM)': 1.4,
 'Muscle Mass (MM)': 4.7,
 'Obesity (%)': 0.4,
 'Total Fat Content (TFC)': 3.1,
 'Visceral Fat Area (VFA)': 0.9,
 'Visceral Muscle Area (VMA) (Kg)': 18.9,
 'Glucose': 69.0,
 'Total Cholesterol (TC)': 60.0,
 'Low Density Lipoprotein (LDL)': 11.0,
 'High Density Lipoprotein (HDL)': 25.0,
 'Triglyceride': 1.39,
 'Aspartat Aminotransferaz (AST)': 8.0,
 'Alanin Aminotransferaz (ALT)': 3.0,
 'Alkaline Phosphatase (ALP)': 7.0,
 'Creatinine': 0.46,
 'Glomerular Filtration Rate (GFR)': 10.6,
 'C-Reactive Protein (CRP)': 0.0,
 'Hemoglobin (HGB)': 8.5,
 'Vitamin D': 3.5}

In [31]:
discrete_features=[]
for i in df.columns:
    
    if df[i].nunique()<10:

        discrete_features.append(df[[i]].value_counts())

discrete_features

[Gallstone Status
 0                   161
 1                   158
 Name: count, dtype: int64,
 Gender
 0         162
 1         157
 Name: count, dtype: int64,
 Comorbidity
 0              217
 1               99
 3                2
 2                1
 Name: count, dtype: int64,
 Coronary Artery Disease (CAD)
 0                                307
 1                                 12
 Name: count, dtype: int64,
 Hypothyroidism
 0                 310
 1                   9
 Name: count, dtype: int64,
 Hyperlipidemia
 0                 311
 1                   8
 Name: count, dtype: int64,
 Diabetes Mellitus (DM)
 0                         276
 1                          43
 Name: count, dtype: int64,
 Hepatic Fat Accumulation (HFA)
 0                                 129
 2                                 122
 1                                  41
 3                                  26
 4                                   1
 Name: count, dtype: int64]

In [8]:
X=df.drop('Gallstone Status',axis=1)
y=df['Gallstone Status']

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline=make_pipeline(StandardScaler())


In [ ]:
from sklearn.compose import make_column_transformer

num_features=X.select_dtypes(exclude='O').columns

continious_features=[]
for i in num_features:
    if X[i].nunique()>10:
        continious_features.append(i)
    
transformer=make_column_transformer(
    (num_pipeline,continious_features),remainder='passthrough'
)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
X_train_transformed=transformer.fit_transform(X_train)
X_test_transformed=transformer.transform(X_test)
with open('Transformer.pkl','wb') as f:
    pickle.dump(transformer,f)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

models={
    'LogisticRegression':LogisticRegression(),
    'Support_Vector_Machine':svm.SVC(),
    'GaussianNB':GaussianNB(),
    'KNeighborsClassifier':KNeighborsClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier()
}

best_models={}

for i in range(len(models.values())):

    model=list(models.values())[i]
    model.fit(X_train_transformed,y_train)

    y_pred=model.predict(X_test_transformed)

    acc=accuracy_score(y_test,y_pred)
    conf=confusion_matrix(y_test,y_pred)

    name=list(models.keys())[i]

    print(f'----------------{name}----------------')
    print(f'Accuracy of model --> {acc}\n')
    print(f'Confussion Matrix is --> \n{conf}\n\n')
    if acc>0.80:
        best_models[name]=acc


print(f'\n\n----------------------->>>>Without Standard Scalar Transformer<<<<-----------------------\n\n')


for i in range(len(models.values())):

    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred=model.predict(X_test)

    acc=accuracy_score(y_test,y_pred)
    conf=confusion_matrix(y_test,y_pred)

    name=list(models.keys())[i]

    print(f'----------------{name}----------------')
    print(f'Accuracy of model --> {acc}\n')
    print(f'Confussion Matrix is --> \n{conf}\n\n')
    if acc>0.80:
        best_models[name]=acc


----------------LogisticRegression----------------
Accuracy of model --> 0.78125

Confussion Matrix is --> 
[[29  4]
 [10 21]]


----------------Support_Vector_Machine----------------
Accuracy of model --> 0.75

Confussion Matrix is --> 
[[29  4]
 [12 19]]


----------------GaussianNB----------------
Accuracy of model --> 0.53125

Confussion Matrix is --> 
[[32  1]
 [29  2]]


----------------KNeighborsClassifier----------------
Accuracy of model --> 0.515625

Confussion Matrix is --> 
[[22 11]
 [20 11]]


----------------DecisionTreeClassifier----------------
Accuracy of model --> 0.71875

Confussion Matrix is --> 
[[25  8]
 [10 21]]


----------------RandomForestClassifier----------------
Accuracy of model --> 0.828125

Confussion Matrix is --> 
[[29  4]
 [ 7 24]]


----------------AdaBoostClassifier----------------
Accuracy of model --> 0.8125

Confussion Matrix is --> 
[[29  4]
 [ 8 23]]




----------------------->>>>Without Standard Scalar Transformer<<<<-----------------------



/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


----------------RandomForestClassifier----------------
Accuracy of model --> 0.8125

Confussion Matrix is --> 
[[28  5]
 [ 7 24]]


----------------AdaBoostClassifier----------------
Accuracy of model --> 0.8125

Confussion Matrix is --> 
[[29  4]
 [ 8 23]]




In [14]:
best_models

{'RandomForestClassifier': 0.8125,
 'AdaBoostClassifier': 0.8125,
 'LogisticRegression': 0.859375}

In [15]:
# HyperTunning Logistic Regression 
from sklearn.model_selection import GridSearchCV

params={
    'penalty':['l1','l2','elasticnet'],
    'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
}
logistic=LogisticRegression() 
grid_logistic=GridSearchCV(estimator=logistic,param_grid=params,cv=5,n_jobs=-1)
grid_logistic.fit(X_train,y_train)


/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.w

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [16]:
grid_logistic.best_params_

{'penalty': 'l2', 'solver': 'lbfgs'}

In [17]:
logistic=LogisticRegression(penalty= 'l2', solver= 'lbfgs',random_state=42)
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)
acc=accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(f'Accuracy --> {acc}\nConfussion Matrix -->\n {conf}')

Accuracy --> 0.859375
Confussion Matrix -->
 [[30  3]
 [ 6 25]]


/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# HyperTune RandomForest

params={
    'n_estimators':[25,50,100,150,200,300,400,500,1000],
    'criterion':['gini', 'entropy', 'log_loss'],
    'max_features':['sqrt', 'log2'],
    'class_weight':['balanced', 'balanced_subsample'] 
}

random_forest=RandomForestClassifier()
grid_Random=GridSearchCV(estimator=random_forest,param_grid=params,n_jobs=-1,cv=5)
grid_Random.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [25, 50, 100, 150, 200, 300, 400, 500,
                                          1000]})

In [19]:
grid_Random.best_params_

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_features': 'sqrt',
 'n_estimators': 300}

In [25]:
random_forest=RandomForestClassifier(class_weight='balanced', n_estimators=300,random_state=42)
random_forest.fit(X_train,y_train)
y_pred=random_forest.predict(X_test)
acc=accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(f'Accuracy --> {acc}\nConfussion Matrix -->\n {conf}')

Accuracy --> 0.8125
Confussion Matrix -->
 [[28  5]
 [ 7 24]]


In [21]:
# HyperTune AdaBoost

params={
    'n_estimators': [50,100,150,200,300,400,1000],
    'learning_rate': [0.01,0.001,0.1,1],
    'algorithm': ['SAMME', 'SAMME.R'] 
}
adaBoost=AdaBoostClassifier()
grid_ADA=GridSearchCV(estimator=adaBoost,param_grid=params,n_jobs=-1,cv=5)
grid_ADA.fit(X_train,y_train)

/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
/home/varun-kasnia/anaconda3/envs/dl

GridSearchCV(cv=5, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': [0.01, 0.001, 0.1, 1],
                         'n_estimators': [50, 100, 150, 200, 300, 400, 1000]})

In [22]:
grid_ADA.best_params_

{'algorithm': 'SAMME', 'learning_rate': 1, 'n_estimators': 400}

In [23]:
adaBoost=AdaBoostClassifier(algorithm='SAMME', learning_rate= 1, n_estimators= 400,random_state=42)
adaBoost.fit(X_train,y_train)
y_pred=adaBoost.predict(X_test)
acc=accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(f'Accuracy --> {acc}\nConfussion Matrix -->\n {conf}')


/home/varun-kasnia/anaconda3/envs/dl/lib/python3.11/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


Accuracy --> 0.828125
Confussion Matrix -->
 [[28  5]
 [ 6 25]]


In [27]:
with open('Logistic.pkl','wb') as f:
    pickle.dump(logistic,f)

# Conclusion that best model is Logistic Regression 
## Accuracy --> 85.93%
### with params  {'penalty': 'l2', 'solver': 'lbfgs'}